services:
  clearcut:
    build: .
    container_name: clearcut
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_FILE_SIZE=10485760  # 10MB
      - ALLOWED_EXTENSIONS=jpg,jpeg,png,webp
      - TEMP_DIR=/tmp/clearcut
    volumes:
      - /tmp/clearcut:/tmp/clearcut
    mem_limit: 1.5g
    cpus: 1.8